// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-members.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-members.ts
var list_members_default = defineTool({
  name: "list_members",
  title: "List members",
  description: "List members, optionally filtered by name/rafaqat number search text or status. Returns membership and payment totals.",
  inputSchema: {
    search: z.string().trim().optional().describe("Match against member name or rafaqat number."),
    status: z.enum(["active", "inactive", "completed"]).optional().describe("Filter by member status."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("members").select(
      "id, full_name, father_name, phone, rafaqat_no, membership_type, status, installment_option, paid_installments, total_installments, total_paid, total_required, remaining_amount, membership_start_date"
    ).order("full_name").limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`full_name.ilike.%${search}%,rafaqat_no.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { members: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-member.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_member_default = defineTool2({
  name: "get_member",
  title: "Get member",
  description: "Get one member's full record together with their payment history, by member id.",
  inputSchema: {
    member_id: z2.string().uuid().describe("The member's id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ member_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: member, error } = await supabase.from("members").select("*").eq("id", member_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!member) return { content: [{ type: "text", text: "Member not found" }], isError: true };
    const { data: payments, error: payErr } = await supabase.from("payments").select("id, amount, payment_date, payment_method, receipt_number, remarks").eq("member_id", member_id).order("payment_date", { ascending: false });
    if (payErr) return { content: [{ type: "text", text: payErr.message }], isError: true };
    const result = { member, payments: payments ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-payments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_payments_default = defineTool3({
  name: "list_payments",
  title: "List payments",
  description: "List recorded membership payments, newest first, optionally within a date range.",
  inputSchema: {
    from_date: z3.string().trim().optional().describe("Only payments on or after this date (YYYY-MM-DD)."),
    to_date: z3.string().trim().optional().describe("Only payments on or before this date (YYYY-MM-DD)."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("payments").select("id, member_id, amount, payment_date, payment_method, receipt_number, remarks, members(full_name, rafaqat_no)").order("payment_date", { ascending: false }).limit(limit ?? 50);
    if (from_date) query = query.gte("payment_date", from_date);
    if (to_date) query = query.lte("payment_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { payments: data ?? [], count: data?.length ?? 0, total_amount: total }
    };
  }
});

// src/lib/mcp/tools/record-payment.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var record_payment_default = defineTool4({
  name: "record_payment",
  title: "Record payment",
  description: "Record a membership payment for a member. Creates a new payment row.",
  inputSchema: {
    member_id: z4.string().uuid().describe("The member the payment belongs to."),
    amount: z4.number().positive().describe("Payment amount."),
    payment_date: z4.string().trim().optional().describe("Payment date (YYYY-MM-DD). Defaults to today."),
    payment_method: z4.string().trim().optional().describe("How the payment was made, e.g. cash or bank."),
    remarks: z4.string().trim().optional().describe("Optional note about this payment.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ member_id, amount, payment_date, payment_method, remarks }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("payments").insert({
      member_id,
      amount,
      payment_date,
      payment_method,
      remarks,
      created_by: ctx.getUserId()
    }).select("id, member_id, amount, payment_date, payment_method, receipt_number, remarks");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { payment: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-donations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_donations_default = defineTool5({
  name: "list_donations",
  title: "List fund donations",
  description: "List fund donations, newest first, optionally within a date range.",
  inputSchema: {
    from_date: z5.string().trim().optional().describe("Only donations on or after this date (YYYY-MM-DD)."),
    to_date: z5.string().trim().optional().describe("Only donations on or before this date (YYYY-MM-DD)."),
    limit: z5.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("donations").select("id, donor_name, amount, donation_date, contact_number, description").order("donation_date", { ascending: false }).limit(limit ?? 50);
    if (from_date) query = query.gte("donation_date", from_date);
    if (to_date) query = query.lte("donation_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { donations: data ?? [], count: data?.length ?? 0, total_amount: total }
    };
  }
});

// src/lib/mcp/tools/add-donation.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var add_donation_default = defineTool6({
  name: "add_donation",
  title: "Add fund donation",
  description: "Record a new donation into the fund.",
  inputSchema: {
    donor_name: z6.string().trim().min(1).describe("Name of the donor."),
    amount: z6.number().positive().describe("Donated amount."),
    donation_date: z6.string().trim().optional().describe("Donation date (YYYY-MM-DD). Defaults to today."),
    contact_number: z6.string().trim().optional().describe("Donor contact number."),
    description: z6.string().trim().optional().describe("Optional note about this donation.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ donor_name, amount, donation_date, contact_number, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("donations").insert({
      donor_name,
      amount,
      donation_date,
      contact_number,
      description,
      created_by: ctx.getUserId()
    }).select("id, donor_name, amount, donation_date, contact_number, description");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { donation: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/fund-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var fund_summary_default = defineTool7({
  name: "fund_summary",
  title: "Fund summary",
  description: "Summarise the organisation's finances: member counts, total membership payments, donations, expenses and the resulting balance.",
  inputSchema: {
    from_date: z7.string().trim().optional().describe("Only count records on or after this date (YYYY-MM-DD)."),
    to_date: z7.string().trim().optional().describe("Only count records on or before this date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const sum = (rows) => (rows ?? []).reduce((total, row) => total + Number(row.amount ?? 0), 0);
    const range = (query, column) => {
      let q = query;
      if (from_date) q = q.gte(column, from_date);
      if (to_date) q = q.lte(column, to_date);
      return q;
    };
    const [payments, donations, expenses, members] = await Promise.all([
      range(supabase.from("payments").select("amount"), "payment_date"),
      range(supabase.from("donations").select("amount"), "donation_date"),
      range(supabase.from("expenses").select("amount"), "expense_date"),
      supabase.from("members").select("status, total_paid, total_required, remaining_amount")
    ]);
    const failure = [payments, donations, expenses, members].find((r) => r.error);
    if (failure) return { content: [{ type: "text", text: failure.error.message }], isError: true };
    const memberRows = members.data ?? [];
    const totalPayments = sum(payments.data);
    const totalDonations = sum(donations.data);
    const totalExpenses = sum(expenses.data);
    const summary = {
      members_total: memberRows.length,
      members_active: memberRows.filter((m) => m.status === "active").length,
      total_payments: totalPayments,
      total_donations: totalDonations,
      total_expenses: totalExpenses,
      balance: totalPayments + totalDonations - totalExpenses,
      outstanding_from_members: memberRows.reduce(
        (t, m) => t + Number(m.remaining_amount ?? 0),
        0
      )
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-activities.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var list_activities_default = defineTool8({
  name: "list_activities",
  title: "List activities",
  description: "List logged organisation activities and announcements, newest first.",
  inputSchema: {
    limit: z8.number().int().min(1).max(200).optional().describe("Max rows to return (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("activities").select("id, message, activity_date, created_at").order("activity_date", { ascending: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { activities: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/log-activity.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.25.76";
var log_activity_default = defineTool9({
  name: "log_activity",
  title: "Log activity",
  description: "Add an activity or announcement entry to the organisation's activity log.",
  inputSchema: {
    message: z9.string().trim().min(1).describe("What happened."),
    activity_date: z9.string().trim().optional().describe("Activity date (YYYY-MM-DD). Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ message, activity_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("activities").insert({ message, activity_date, created_by: ctx.getUserId() }).select("id, message, activity_date, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { activity: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nwvqyispcoajymwdsixc";
var mcp_default = defineMcp({
  name: "uc-fund-keeper",
  title: "UC Fund Keeper",
  version: "0.1.0",
  instructions: "Tools for UC Fund Keeper, a membership and fund management app. Use `list_members` and `get_member` to look up members and their payment history, `list_payments` and `record_payment` for membership payments, `list_donations` and `add_donation` for the fund, `fund_summary` for overall financial totals, and `list_activities` / `log_activity` for the activity log. All tools act as the signed-in user of the app.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_members_default,
    get_member_default,
    list_payments_default,
    record_payment_default,
    list_donations_default,
    add_donation_default,
    fund_summary_default,
    list_activities_default,
    log_activity_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
